README.rst
=> Minor spelling error fix.

pynndescent/distances.py, pynndescent/rp_trees.py, pynndescent/tests/test_pynndescent_.py, pynndescent/utils.py
This ports some of the changes that have been made in umap that cause pynndescent to diverge back over to this repo. This includes two tests. Support for sparse arrays is not included.
=> Port changes in umap's nndescent code over to pynndescent

pynndescent/tests/test_distances.py
Expands the distance tests, similarly to https://github.com/lmcinnes/umap/pull/223
=> individual distance tests

pynndescent/__init__.py, pynndescent/pynndescent_.py, pynndescent/rp_trees.py, pynndescent/tests/test_pynndescent_.py, pynndescent/tests/test_threaded.py, pynndescent/threaded.py, pynndescent/utils.py, setup.py
A whole lot of whitespace changes, but no functional changes.
=> Reformat code with black

README.rst, pynndescent/pynndescent_.py, pynndescent/rp_trees.py, pynndescent/sparse.py
[lgtm](https://lgtm.com) is already analysing pynndescent, and it did spot some fixable issues (unused imports), so might as well add the badge.
Also, it thinks the code quality is A+.
=> Add lgtm badges

pynndescent/pynndescent_.py, pynndescent/tests/test_pynndescent_.py, pynndescent/utils.py
Adds verbose flag to `NNDescent` and `PyNNDescentTransformer` and adds the timestamped messages I added to UMAP.
=> Add verbose flag

pynndescent/pynndescent_.py, pynndescent/rp_trees.py, pynndescent/sparse.py, pynndescent/tests/test_pynndescent_.py
Minor code changes, cherry-picked from a sea of mainly unhelpful pylint warnings and info.
=> Pylint fixes

appveyor.yml, azure-pipelines.yml, pynndescent/__init__.py
Add the `__version__` attribute, using the same technique as UMAP.
=> Add __version__ attribute

pynndescent/pynndescent_.py, pynndescent/rp_trees.py, pynndescent/tests/test_threaded.py, pynndescent/threaded.py
Constructing the leaf array is done in a single thread still (since
it was found to be relatively fast), but the heap updates are done
in multiple threads.
=> Threaded implementation of RP trees initialization

pynndescent/tests/test_pynndescent_.py
Splitting cosine hang test to avoid test failure uncovered in https://github.com/lmcinnes/pynndescent/pull/40.
The test as it stands is a regression test for UMAP hanging with the cosine metric in the face of lots of all-zero and duplicate data. Success should probably just be if that chunk of codes completes without a recursion error.
I've added a second, smaller test to ensure for non-zero deduplicated data that sensible results are obtained.
=> split cosine hang test into two tests

pynndescent/tests/test_pynndescent_.py, pynndescent/tests/test_threaded.py
Fix warnings I introduced into some tests.
=> Use assert_equal not assert_equals

CODE_OF_CONDUCT.md, CONTRIBUTING.md
These are just the contribution files from UMAP, but I added a section to `CONTRIBUTING.md` about running black on any PRs to avoid the travis CI showing a failed check.
=> Add contribution details.

pynndescent/pynndescent_.py, pynndescent/threaded.py
This logging is the same as UMAP's.
=> Log iteration of nn-descent loop in verbose mode

pynndescent/pynndescent_.py, pynndescent/tests/test_threaded.py, pynndescent/threaded.py
from a joblib parallel_backend context manager.
=> Fix bug where default n_jobs was not being correctly interpreted

pynndescent/tests/test_threaded.py, pynndescent/threaded.py
=> Make heap updates a float32

pynndescent/__init__.py
=> Slightly more careful workaround

pynndescent/pynndescent_.py
Allow for parallelization over multiple points in batch querying.
=> Optional parallel query batch

pynndescent/pynndescent_.py, pynndescent/tests/test_pynndescent_.py
Previously the querying data (search graphs, compiled search function etc.) were not properly rebuilt after ``update`` added new data. We now ensure that this is handled correctly.
=> Ensure query after to update works correctly (fixes #180)

pynndescent/pynndescent_.py
Got this warning and noticed some bad formatting, figured I'd fix it. 👍
=> [small fix] add spaces to warning message

doc/how_to_use_pynndescent.ipynb, doc/pynndescent_in_pipelines.ipynb
A "t" was missing in "how fast was the nearest neighbor".
=> Fix typos in docu

pynndescent/tests/test_distances.py
Sklearn pairwise_distances no longer support np.matrix as input
=> Update tests to fix #207

pynndescent/tests/test_distances.py
Context: https://github.com/NixOS/nixpkgs/pull/248481
=> tests: fix compat with scipy 1.11

pynndescent/distances.py, pynndescent/pynndescent_.py, pynndescent/rp_trees.py, pynndescent/tests/test_distances.py, pynndescent/tests/test_pynndescent_.py
as 1bit embedding vectors become more common it has become worth the effort to support bitpacked (into uint8) vectors of binary data via hamming and jaccard distance (notionally equivalent to inner-product and cosine distances). This should add basic support via the metric ``"bit_hamming"`` and ``"bit_jaccard"`` assumiong data is passed as an ndarray of dtype ``np.uint8``.
=> Add support for bitpacked vectors with hamming and jaccard

azure-pipelines.yml, pynndescent/tests/test_pynndescent_.py
This will let us easily test installing with pre-release versions of dependencies
=> Add pre-release parameter in pipelines
