lmcinnes/pynndescent

- pynndescent/pynndescent_.py
- pynndescent/threaded.py
- pynndescent/utils.py
- test_threaded.py
Currently, pynndescent doesn't take full advantage of multiple cores on a machine. There are some methods annotated with the Numba [parallel](http://numba.pydata.org/numba-doc/latest/user/parallel.html) option, but these don't provide any noticeable speed up when more cores are available.
This PR allows nearest neighbor computation to take advantage of multiple cores by processing heaps in parallel chunks. The basic idea is an application of the MapReduce approach described in section 2.8 of [Efficient K-Nearest Neighbor Graph Construction for Generic Similarity Measures](http://www.cs.princeton.edu/cass/papers/www11.pdf) by Dong et al.
Note that in this PR all computation is carried out on a single machine using the standard Python …
> Multi-threaded implementation

- pynndescent/tests/test_pynndescent_.py
Fixes #10, and includes the test written by @pavlin-policar.
Note that the non-determinism was fixed as a part of #12, when `numba.prange` was replaced with `range` in the `build_candidates` candidates function.
> Test that setting random_state for NNDescent produces deterministic outputs

- pynndescent/pynndescent_.py
- pynndescent/rp_trees.py
- pynndescent/sparse.py
- pynndescent/tests/test_distances.py
- pynndescent/tests/test_pynndescent_.py
- pynndescent/tests/test_threaded.py
- pynndescent/threaded.py
- pynndescent/utils.py
> Port sparse matrix support from umap

- README.rst
- appveyor.yml
Good news: this PR introduces CI on Windows.
Bad news: tests are failing.
Ok news:  it seems reproducible on my machine, so I can probably start fixing it.
@lmcinnes: you will need to click on the badge and then activate the repo on Appveyor to start this going. If you don't have an account you can give it access via github, similarly to travis-ci. Speaking of which, the travis ci also needs to be activated by the same method (click its badge and so on).
> Windows CI with Appveyor

- pynndescent/tests/test_distances.py
In `test_distances.py`, the `binary_data` boolean matrix has zeros added to it, which causes a large number of DataConversion warnings. I've changed the zeros to 'False', which hopefully preserves the meaning of the tests.
> Fix DataConversion warnings 

- pynndescent/pynndescent_.py
- pynndescent/rp_trees.py
- pynndescent/tests/test_pynndescent_.py
- pynndescent/tests/test_threaded.py
- pynndescent/utils.py
Relates to https://github.com/lmcinnes/pynndescent/issues/37
This isn't intended to be merged in its current state, this is just to conveniently show the current state of the diffs. The things to look at are:
* numba decorations. Sometimes UMAP has more, sometimes it's vice versa. I don't know which ones are necessary or helpful.
* In `new_build_candidates`, there is a test failure when using `numba.prange`, so I have commented it out and used  a plain old `range`.
* The biggest change is to the nearest neighbor descent routine, which introduces a set to keep track of previously seen pairs, and unchecked heap pushes. There are two test failures due to a much lower expected accuracy, unless I comment out the use of the unchecked heap push in the first loop in the nn descent iteration. Not …
> backport UMAP 0.4dev changes

- pynndescent/pynndescent_.py
Now it will only be copied if the type needs to be changed. This is
consistent with UMAP.
> Avoid an unnecessary copy of the data matrix.

- pynndescent/distances.py
The docstring with equations in needed to be marked as raw strings, due to the presence of backslashes.
I verified this works by manually creating the documentation with Sphinx.
> Fix doc backslash

- setup.py
Relates to #48.
Pyroma thinks that the `author` and `author_email` fields should be present.
Also, `zip_safe` should be explicitly set. The default is `True`, so I've left it at that. I *think* it's [ok for `zip_safe = True`](https://setuptools.readthedocs.io/en/latest/setuptools.html#setting-the-zip-safe-flag), but I don't know what the effect of Numba is.
> Fix pyroma complaints

- appveyor.yml
Windows CI is not picking up dependencies automatically, because we were installing them via conda. Instead, use `pip` and `requirements.txt`.
> appveyor: use requirements.txt for dependencies

- pynndescent/pynndescent_.py
Some applications don't need the search capability (e.g. UMAP), just the neighbors graph. Constructing the search graph is expensive for larger datasets, so by constructing it lazily the cost is avoided in these cases.
> Initialise search graph lazily

- pynndescent/pynndescent_.py
- pynndescent/tests/test_threaded.py
- pynndescent/threaded.py
- requirements.txt
This replaces `concurrent.futures.ThreadPoolExecutor` with [joblib](https://joblib.readthedocs.io/en/latest/index.html). Joblib is used by scikit-learn, and has other backends, such as multiprocessing and Dask, which could be attractive in the future. I have benchmarked the threading backend with up to 64 threads and a range of data sizes (up to 1M rows) and the results are comparable with `ThreadPoolExecutor`.
Another nice thing about Joblib is that it allows parallelism to be specified outside the library using a [context manager](https://joblib.readthedocs.io/en/latest/parallel.html#joblib.parallel_backend). So for UMAP you could run with threads using something like this (once UMAP uses pynndescent of course):
```python
with parallel_backend('threading', n_jobs=8):
embedding = …
```
> Use joblib for parallelization.

- setup.py
`scikit-learn` (<0.21) does not explicitly declare joblib as an external dependency (https://github.com/scikit-learn/scikit-learn/pull/13531).
> Add joblib to install_requires

- pynndescent/pynndescent_.py
- pynndescent/rp_trees.py
- pynndescent/tests/test_threaded.py
Brings `n_trees` and `n_iters` defaults into line with UMAP, and fixes #51.
> Better defaults

- pynndescent/pynndescent_.py
- pynndescent/tests/test_pynndescent_.py
Fixes #73 
Still needs a test, but I can add that tomorrow.
I've also reversed the dimensions specified by the `.transform` docs since a) I'm using the indices as they're returned and b) it fits the API of `KNeighborsTransformer` this way.
> Start fix for tranformer return shape

- pynndescent/pynndescent_.py
Just a minor issue that I noticed while reading the docstring for `NNDescent`. According to the NN-descent paper, larger values of constant `rho` lead to more accurate indexes at the cost of more computation. In case your code definition of `rho` is the different from the paper's definition, please ignore and I will close the PR :).
> Fix docstring for parameter 'rho'

- README.rst
- pynndescent/distances.py
- pynndescent/tests/test_distances.py
- pynndescent/tests/test_rank.py
Addresses issue https://github.com/lmcinnes/umap/issues/319 and https://github.com/lmcinnes/pynndescent/issues/85
I know tests are missing, but I am not 100% sure how to add them the right way. Guidance welcome.
> Added spearmanr

- MANIFEST.in
The terms of the BSD-2-Clause license requires it.  Also include tests, requirements.txt, and a few additional documentation files.
> Include license in sdist

- pynndescent/distances.py
- pynndescent/rp_trees.py
- pynndescent/sparse.py
- pynndescent/utils.py
It seems like previous Numba versions (up to 0.51.2) may have worked 'by
accident'. When running pynndescent against a recent development version
of Numba. I receievd many errors during test collection of the form:
```
E   numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
E   Storing i64 to ptr of i32 ('dim'). FE type uint32
E
E   File "../miniconda3/envs/umap/lib/python3.7/site-packages/pynndescent/utils.py", line 88:
E   def norm(vec):
E       <source elided>
E       result = 0.0
E       dim = vec.shape[0]
E       ^
E
E   During: lowering "dim = static_getitem(value=$8load_attr.2, index=0, index_var=$const10.3, fn=<built-in function getitem>)" at /Users/vhaenel/git/numba-integration-testing/miniconda3/envs/umap/lib/python3.7/site-packages/pyn …
```
> fixes for Numba 0.53.0dev0

- pynndescent/distances.py
- pynndescent/rp_trees.py
- pynndescent/sparse.py
- pynndescent/utils.py
As `intp` is the more portable option.
Followup from #113
> fix types: int64->intp

- .travis.yml
- appveyor.yml
- azure-pipelines.yml
- ci/install.sh
- ci/test.sh
- pynndescent/tests/conftest.py
- pynndescent/tests/test_distances.py
- pynndescent/tests/test_pynndescent_.py
- pynndescent/tests/test_rank.py
- requirements.txt
As promised in [#578](https://github.com/lmcinnes/umap/pull/578#issuecomment-777023951), this PR migrates and rewrites `pynndescent` test suite to make it compatible with `pytest`.
In addition: 
- Python 3.8 pipelines have been added in CI
- CI scripts should be updated accordingly to use Pytest (with and without coverage support).
*EDIT*: Bear with me while I do test and fix CI scripts :)
> Dropping Nose dependency and PyTest migration

- pynndescent/pynndescent_.py
I'm getting the following error while pickling a fitted UMAP object. While this happening using umap it looks like the problem is in pynndescent
```
Traceback (most recent call last):
File "pipeline.py", line 236, in <module>
fire.Fire()
File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
component_trace = _Fire(component, args, parsed_flag_args, context, name)
File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
component, remaining_args = _CallAndUpdateTrace(
File "/usr/local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
component = fn(*varargs, **kwargs)
File "pipeline.py", line 72, in process
joblib.dump(doc_to_vec_transform, f'/doc2vec.pk.gz.{site}')
File …
```
> Fix incorrect execution path when pickling rp_trees for sparse data.

- pynndescent/pynndescent_.py
This is just the other half I missed adding to #118
To fix this kind of exception when unpickling for sparse data:
```
:/setstate
File "/usr/local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 289, in _runPass
mutated |= check(pss.run_pass, internal_state)
File "/usr/local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 262, in check
mangled = func(compiler_state)
File "/usr/local/lib/python3.8/site-packages/numba/core/typed_passes.py", line 94, in run_pass
typemap, return_type, calltypes = type_inference_stage(
File "/usr/local/lib/python3.8/site-packages/numba/core/typed_passes.py", line 72, in type_inference_stage
infer.propagate(raise_errors=raise_errors)
File "/usr/local/lib/python3.8/site-packages/numba/core/typeinfer.py", line 1071, in …
```
> Fix incorrect execution path when unpickling rp_trees for sparse data.

- pynndescent/tests/test_pynndescent_.py
Modify tests to write to an in memory buffer instead of the filesystem
in order to avoid issues where tests are not run in an environment in
which the current directory is writeable.
> Don't rely on being able to write to the filesystem in tests.

- pynndescent/pynndescent_.py
- setup.py
As discussed in #139. This PR:
* Adds a deprecation notice to the `n_search_trees` parameter in `PyNNDescentTransformer` and `NNDescent` docstring. The latter did not actually mention the parameter, so I added it for consistency's sake. I'm sure users will be overjoyed to discover the documentation of a parameter that they should no longer use. You're welcome.
* Increments the (patch release) version in `setup.py` to `0.5.5` to avoid confusion over which version the deprecation is occurring in.
I copied the docstring formatting from docstring in Pandas. The sphinx HTML output seems perfectly reasonable.
> Add deprecation notice to n_search_trees parameter docstring

- pynndescent/pynndescent_.py
(this PR has nothing to do with dask, that's just what I named my fork)
Since I [tweeted](https://twitter.com/james_t_webber/status/1476962551384711168) about it I figured I should fix the problem with the docs. This changes the docstrings so that they match the actual defaults.
The only case where this is a major change is the description of the `low_memory` option. The previous docs suggested it was slower, but it often isn't. Also, I don't think the high memory algorithm has been getting tested thoroughly and might have some regressions (e.g. I found https://github.com/lmcinnes/pynndescent/issues/135 last summer). It might be a good idea to add a warning to that effect.
As another very minor change here, I removed the class inheritance from `object`, which is unnecessary in python 3 …
> fix docstring for NNDescent

- .travis.yml
- appveyor.yml
- azure-pipelines.yml
- pynndescent/pynndescent_.py
- pynndescent/rp_trees.py
- pynndescent/sparse.py
Sparse binary distances were slow due to using naive intersection / union implementations. If we assume indices are sorted (which they should be as we require it elsewhere) then we can go much faster.
> Update sparse distances

- pynndescent/distances.py
- pynndescent/tests/test_distances.py
Have seen a lot of failed tests, I think this should fix it...the `wminkowski` distance metric was removed in scipy 1.8.0.
edit: having verified that was the issue, I'm going to update this with a better option. scipy's version of`minkowski` now supports the `w` parameter. Rather than skipping the test it should just use that function if possible, so that the numba version is still tested.
> fix wminkowski implementation, and test for scipy >= 1.8.0

- pynndescent/optimal_transport.py
- pynndescent/pynndescent_.py
- pynndescent/rp_trees.py
- pynndescent/sparse.py
- pynndescent/sparse_nndescent.py
- pynndescent/utils.py
This is a pull request addressing several issues indicating that `pynndescent` segfaults randomly:
- https://github.com/lmcinnes/umap/issues/747
- https://github.com/lmcinnes/umap/issues/421
- https://github.com/lmcinnes/pynndescent/issues/142
- And maybe https://github.com/lmcinnes/pynndescent/issues/128
The segfaults are a result of this known numba issue: 
- https://github.com/numba/numba/pull/7522
Using `cache=True` and `parallel=True` only caches a numba function for the original number of designated threads. If the thread count being used is changed then numba segfaults.
The fix involves not caching any numba functions that utilize `parallel=True`. Most functions are still cached so import times should not be noticeably different.
> fix: remove cache=True from numba functions that implement parallel=True

- pynndescent/distances.py
- pynndescent/pynndescent_.py
- pynndescent/rp_trees.py
- pynndescent/sparse.py
- pynndescent/tests/test_pynndescent_.py
- pynndescent/tests/test_rank.py
- pynndescent/utils.py
With every call of  `nn_descent.update(xs)`, `nn_descent.n_trees` was divided by `3` which caused empty search forests (since the number of trees dropped to 0).
This is now fixed and the correspodning test is included in the tests (`test_tree_numbers_after_multiple_updates(n_trees)`).
After that, the code was formatted with `black` which changed some other files that I haven't touched otherwise.
> Fixing the bug with n_trees introduced when fixing #180

- pynndescent/pynndescent_.py
- pynndescent/rp_trees.py
- pynndescent/tests/conftest.py
- pynndescent/tests/test_pynndescent_.py
- setup.py
The code now accepts trees with no splits (previously an exception was raised) and computes the dimension of the hyperplane directly (from `data.shape[1]`) - as discussed in #178
> Accepting rp trees with no splits

- pynndescent/distances.py
- pynndescent/tests/test_distances.py
- pynndescent/tests/test_pynndescent_.py
I'm guessing that a previous run of `black` put these split strings onto the same line. It was bugging me.
> [minor] clean up some strings

- pynndescent/__init__.py
- setup.py
pkg_resources was causing errors when using our package on google colab due to its internal caching (https://github.com/sacdallago/bio_embeddings/issues/160, https://github.com/sacdallago/bio_embeddings/issues/123), so I've replaced it with importlib.metadata. I've done the same change before for huggingface/transformers (ttps://github.com/huggingface/transformers/issues/10964). Also note that pkg_resources is deprecated in favor of importlib.metadata (https://setuptools.readthedocs.io/en/latest/pkg_resources.html). For python versions older than 3.8, I'm using the official importlib-metadata backport.
> Replace pkg_resources with importlib.metadata

- pynndescent/tests/test_distances.py
Since the update from 0.5.2 to 0.5.7, we see the following failure on POWER architecture in Debian:
```
=================================== FAILURES ===================================
________________________________ test_spearmanr ________________________________
def test_spearmanr():
x = np.random.randn(100)
y = np.random.randn(100)
scipy_expected = stats.spearmanr(x, y)
r = dist.spearmanr(x, y)
>       assert_array_equal(r, scipy_expected.correlation)
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 1 / 1 (100%)
E       Max absolute difference: 1.38777878e-17
E       Max relative difference: 2.63709617e-16
E        x: array(0.052625)
E        y: array(0.052625)
pynndescent/tests/test_distances.py:312: AssertionError
```
Full build log: …
> Increase test_spearmanr tolerance

- pynndescent/distances.py
- pynndescent/tests/test_distances.py
The `spearmanr` distance currently returns the actual Spearman rank-correlation coefficient, which behaves like a similarity measure rather than a dissimilarity measure. I believe this is not what `NNDescent` expects. Rather than using the numpy correlation matrix function, we can use the `correlation` distance after computing the rank transformation. Making this change also resolves a problem where `spearmanr` would return `nan` when both input vectors were identical.
> Make `spearmanr` a dissimilarity measure

- pynndescent/pynndescent_.py
- pynndescent/sparse_nndescent.py
- pynndescent/utils.py
There are currently a number of functions with `cache=True` that take distance metric functions as arguments. If you observe the caching behavior, every query is a cache miss and a new copy of the code is cached each time the function is run (even with the same argument types). The reason for this is that Numba is overly conservative with typing the distance function, including the actual memory address in the type. This means that the type signatures for these functions (almost) never match between different Python invocations.
You can check that the cache for these functions is missed every time by running something like
```python
import numpy as np
import pynndescent
X = np.random.randn(20, 10)
nnd = pynndescent.NNDescent(X, n_neighbors=5) …
```
> Remove caching for functions that take distance metrics as arguments

- pynndescent/tests/test_pynndescent_.py
- pynndescent/utils.py
Fix #241 by replacing `np.infty` with `np.inf`. Hopefully this will be enough to adopt numpy 2.0
Edit: by going through the list in [numpy 2.0 migration guide](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#main-namespace), the only other verb used which will be removed in the future is `np.in1d`  (used in test), to be replaced with [`np.isin`](https://numpy.org/doc/stable/reference/generated/numpy.isin.html) which is available since numpy==1.13.0. As the min version here is 1.17, I felt free to replace it 😁
> patch: replace `np.infty` with `np.inf`
